/**************************************************************************
 * IMPORTS
 ***************************************************************************/

import type {
  EscalateCartDrawerInput,
  EscalateCartDrawerOutput,
} from "@/mcp/tools/escalate_cart_drawer_issue/shapes.js";
import {
  looksLikePlaceholder,
  pickMissingInfoMessage,
  pickWaitMessage,
  translateIssueToEnglish,
  tryPostNoteWithScoring,
  type PostNoteResult,
} from "@/lib/escalation-shared.js";
import { requireStoreAccess } from "@/lib/store-access.js";
import { requireEditorExit } from "@/lib/editor-exit.js";

/**************************************************************************
 * CONSTANTS
 ***************************************************************************/

type MissingField = "editor_link" | "live_preview_url";

// English labels are the single source of truth. Customer-facing replies
// are generated by Claude in the customer's language at runtime; these
// English strings are what we pass to Claude for natural translation.
const MISSING_LABELS_EN: Record<MissingField, string> = {
  editor_link: "the editor link",
  live_preview_url: "the live preview URL",
};

/**************************************************************************
 * NOTE FORMAT
 ***************************************************************************/

interface CartNoteFields {
  issueDescription: string;
  livePreviewUrl: string;
  editorLink: string;
  screenshotUrl?: string;
}

function formatCartNoteContent(fields: CartNoteFields, ticketUrl: string): string {
  // Silently drop placeholder screenshot URLs (already filtered upstream,
  // but defend in depth in case future call sites skip the gate).
  const hasScreenshot =
    fields.screenshotUrl && !looksLikePlaceholder(fields.screenshotUrl);

  const issueLine = hasScreenshot
    ? `Issue: ${fields.issueDescription}, live preview: ${fields.livePreviewUrl}, screenshot: ${fields.screenshotUrl}`
    : `Issue: ${fields.issueDescription}, live preview: ${fields.livePreviewUrl}`;

  return `${issueLine}\nEditor: ${fields.editorLink}\nTicket: ${ticketUrl}`;
}

/**************************************************************************
 * MAIN HANDLER
 ***************************************************************************/

// Dependency injection seam — tests can pass a stub that returns {ready: true}
// to exercise the missing-info gate without hitting Crisp meta API. Production
// always uses the real shared `requireStoreAccess`.
type AccessChecker = typeof requireStoreAccess;

async function escalateCartDrawerIssueHandler(
  input: EscalateCartDrawerInput,
  accessChecker: AccessChecker = requireStoreAccess
): Promise<EscalateCartDrawerOutput> {

  // Check Shopify store access. Cart drawer issues almost always need TS
  // to debug theme code; surface the access requirement before collecting
  // other info.
  const access = await accessChecker(
    input.crisp_session_id ?? "",
    input.customer_last_message_text
  );
  if (!access.ready) {
    return {
      issue_summary: "Need Shopify store access before escalating to the technical team.",
      session_match: undefined,
      ...access.output,
    } as EscalateCartDrawerOutput;
  }

  // Editor-exit gate. Customer must have exited the PageFly editor
  // before TS starts work. Asked AFTER access is granted (granting access
  // doesn't require leaving the editor; exiting matters only when TS is
  // about to debug).
  const editorExit = await requireEditorExit(
    input.user_exited_editor,
    input.customer_last_message_text
  );
  if (!editorExit.ready) {
    return {
      issue_summary:
        "Need confirmation that the customer has exited the editor before escalating.",
      session_match: undefined,
      ...editorExit.output,
    } as EscalateCartDrawerOutput;
  }

  const missing: MissingField[] = [];

  if (!input.editor_link) missing.push("editor_link");
  if (!input.live_preview_url) missing.push("live_preview_url");

  if (input.editor_link && looksLikePlaceholder(input.editor_link)) {
    if (!missing.includes("editor_link")) missing.push("editor_link");
  }
  if (input.live_preview_url && looksLikePlaceholder(input.live_preview_url)) {
    if (!missing.includes("live_preview_url")) missing.push("live_preview_url");
  }

  if (missing.length > 0) {
    const labelsEn = missing.map((key) => MISSING_LABELS_EN[key]).join(", ");
    return {
      issue_summary: "Need more information before escalating to the technical team.",
      is_ready_for_escalation: false,
      missing_info: missing,
      crisp_note: { content: "", formatted_message: "" },
      next_step_for_user: await pickMissingInfoMessage(input.customer_last_message_text, labelsEn),
      note_posted: false,
      note_post_error:
        "Not ready for escalation — Hugo MUST ask the user for the real editor link and live preview URL, then call this tool again with the user's actual values. Do NOT fabricate placeholder URLs.",
    };
  }

  // Past the gate above, both fields are guaranteed present.
  const editorLink = input.editor_link as string;
  const livePreviewUrl = input.live_preview_url as string;
  // Drop placeholder screenshots silently.
  const screenshotUrl =
    input.screenshot_url && !looksLikePlaceholder(input.screenshot_url)
      ? input.screenshot_url
      : undefined;

  // The note (TS-facing) must always be English. Translate if Hugo passed Vietnamese.
  const issueDescriptionEn = await translateIssueToEnglish(input.issue_description);

  const noteResult: PostNoteResult = await tryPostNoteWithScoring({
    hintedSessionId: input.crisp_session_id,
    fields: {
      issueDescription: issueDescriptionEn,
      livePreviewUrl,
      editorLink,
      screenshotUrl,
    },
    providedTicketUrl: input.ticket_url,
    scoringInputs: {
      customerLastMessageText: input.customer_last_message_text,
      screenshotUrl,
      editorLink,
    },
    formatNote: formatCartNoteContent,
  });

  if (noteResult.posted) {
    console.log(
      `[escalate_cart_drawer_issue] match: session=${noteResult.sessionUsed} source=${noteResult.sessionSource} score=${noteResult.match?.score ?? "n/a"} signals=[${noteResult.match?.signalsMatched.join(", ") ?? ""}] posted=true`
    );
  } else {
    console.error(
      `[escalate_cart_drawer_issue] match: posted=false error=${noteResult.error}`
    );
  }

  return {
    issue_summary: input.issue_description,
    is_ready_for_escalation: true,
    missing_info: [],
    crisp_note: {
      content: noteResult.noteContent,
      formatted_message: noteResult.noteContent,
    },
    next_step_for_user: await pickWaitMessage(input.customer_last_message_text),
    note_posted: noteResult.posted,
    note_post_error: noteResult.error,
    session_match: noteResult.match
      ? {
          score: noteResult.match.score,
          signals_matched: noteResult.match.signalsMatched,
          threshold_met: noteResult.match.thresholdMet,
        }
      : undefined,
  };
}

/**************************************************************************
 * EXPORTS
 ***************************************************************************/

export { escalateCartDrawerIssueHandler, formatCartNoteContent };
