/**************************************************************************
 * IMPORTS
 ***************************************************************************/

import type {
  EscalateAnimationInput,
  EscalateAnimationOutput,
} from "@/mcp/tools/escalate_animation_issue/shapes.js";
import {
  filterValidUrls,
  formatReferenceMedia,
  hasAnyReferenceMedia,
  looksLikePlaceholder,
  pickMissingInfoMessage,
  pickWaitMessage,
  translateIssueToEnglish,
  tryPostNoteWithScoring,
  type PostNoteResult,
} from "@/lib/escalation-shared.js";
import { requireStoreAccess } from "@/lib/store-access.js";

/**************************************************************************
 * CONSTANTS
 ***************************************************************************/

type MissingField = "editor_link" | "reference" | "publish_status";

// English labels are the single source of truth. Customer-facing replies
// are generated by Claude in the customer's language at runtime; these
// English strings are what we pass to Claude for natural translation.
const MISSING_LABELS_EN: Record<MissingField, string> = {
  editor_link: "the editor link",
  reference: "a reference (link or attached image/video showing the desired effect)",
  publish_status: "whether the technical team may publish the page or only save it",
};

const PUBLISH_STATUS_LABEL: Record<"published" | "only_save", string> = {
  published: "Allowed to publish",
  only_save: "Only Save",
};

/**************************************************************************
 * NOTE FORMAT
 ***************************************************************************/

interface AnimationNoteFields {
  issueDescription: string;
  editorLink: string;
  referenceUrls: string[];
  customerAttachedFiles: boolean;
  publishStatus: "published" | "only_save";
}

function formatAnimationNoteContent(
  fields: AnimationNoteFields,
  ticketUrl: string
): string {
  const referenceFragment = formatReferenceMedia(
    {
      urls: fields.referenceUrls,
      hasAttachedFiles: fields.customerAttachedFiles,
    },
    "reference"
  );
  const issueLine = referenceFragment
    ? `Issue: ${fields.issueDescription}, ${referenceFragment}`
    : `Issue: ${fields.issueDescription}`;
  const statusLine = PUBLISH_STATUS_LABEL[fields.publishStatus];

  return `${issueLine}\nEditor: ${fields.editorLink}\nTicket: ${ticketUrl}\n${statusLine}`;
}

/**************************************************************************
 * MAIN HANDLER
 ***************************************************************************/

type AccessChecker = typeof requireStoreAccess;

async function escalateAnimationIssueHandler(
  input: EscalateAnimationInput,
  accessChecker: AccessChecker = requireStoreAccess
): Promise<EscalateAnimationOutput> {
  // Animation issues almost always require TS to debug theme code or
  // recreate the effect in the live store. Surface access requirement first.
  const access = await accessChecker(
    input.crisp_session_id ?? "",
    input.customer_last_message_text
  );
  if (!access.ready) {
    return {
      issue_summary: "Need Shopify store access before escalating to the technical team.",
      session_match: undefined,
      ...access.output,
    } as EscalateAnimationOutput;
  }

  const missing: MissingField[] = [];

  if (!input.editor_link || looksLikePlaceholder(input.editor_link)) {
    missing.push("editor_link");
  }
  if (
    !hasAnyReferenceMedia({
      urls: input.reference_urls,
      hasAttachedFiles: input.customer_attached_files,
    })
  ) {
    missing.push("reference");
  }
  if (
    input.publish_status !== "published" &&
    input.publish_status !== "only_save"
  ) {
    missing.push("publish_status");
  }

  if (missing.length > 0) {
    const labelsEn = missing.map((key) => MISSING_LABELS_EN[key]).join(", ");
    return {
      issue_summary: "Need more information before escalating to the technical team.",
      is_ready_for_escalation: false,
      missing_info: missing,
      crisp_note: { content: "", formatted_message: "" },
      next_step_for_user: await pickMissingInfoMessage(
        input.customer_last_message_text,
        labelsEn
      ),
      note_posted: false,
      note_post_error:
        "Not ready for escalation — Hugo MUST ask the user for the real editor link, a reference (link OR attached file), and the publish_status answer. Do NOT fabricate URLs or status values.",
    };
  }

  // Past the gate: editor_link present, at least one reference exists.
  const editorLink = input.editor_link as string;
  const validReferenceUrls = filterValidUrls(input.reference_urls);
  const hasFiles = input.customer_attached_files === true;

  // The note (TS-facing) must always be English. Translate if Hugo passed Vietnamese.
  const issueDescriptionEn = await translateIssueToEnglish(input.issue_description);

  const noteResult: PostNoteResult = await tryPostNoteWithScoring({
    hintedSessionId: input.crisp_session_id,
    fields: {
      issueDescription: issueDescriptionEn,
      editorLink,
      referenceUrls: validReferenceUrls,
      customerAttachedFiles: hasFiles,
      publishStatus: input.publish_status,
    },
    providedTicketUrl: input.ticket_url,
    scoringInputs: {
      customerLastMessageText: input.customer_last_message_text,
      screenshotUrl: validReferenceUrls[0],
      editorLink,
    },
    formatNote: formatAnimationNoteContent,
  });

  if (noteResult.posted) {
    console.log(
      `[escalate_animation_issue] match: session=${noteResult.sessionUsed} source=${noteResult.sessionSource} score=${noteResult.match?.score ?? "n/a"} signals=[${noteResult.match?.signalsMatched.join(", ") ?? ""}] posted=true`
    );
  } else {
    console.error(
      `[escalate_animation_issue] match: posted=false error=${noteResult.error}`
    );
  }

  return {
    issue_summary: input.issue_description,
    is_ready_for_escalation: true,
    missing_info: [],
    crisp_note: {
      content: noteResult.noteContent,
      formatted_message: noteResult.noteContent,
    },
    next_step_for_user: await pickWaitMessage(input.customer_last_message_text),
    note_posted: noteResult.posted,
    note_post_error: noteResult.error,
    session_match: noteResult.match
      ? {
          score: noteResult.match.score,
          signals_matched: noteResult.match.signalsMatched,
          threshold_met: noteResult.match.thresholdMet,
        }
      : undefined,
  };
}

/**************************************************************************
 * EXPORTS
 ***************************************************************************/

export { escalateAnimationIssueHandler, formatAnimationNoteContent };
