/**************************************************************************
 * IMPORTS
 ***************************************************************************/

import type {
  EscalateAppsInput,
  EscalateAppsOutput,
} from "@/mcp/tools/escalate_apps_issue/shapes.js";
import {
  looksLikePlaceholder,
  pickMissingInfoMessage,
  pickWaitMessage,
  pickWrongEditorLinkMessage,
  translateIssueToEnglish,
  tryPostNoteWithScoring,
  makeDedupKey,
  urlAppearsInMessages,
  isEditorLink,
  groundPublishConsent,
  fetchCustomerTexts,
  type PostNoteResult,
} from "@/lib/escalation-shared.js";
import { requireEditorExit } from "@/lib/editor-exit.js";

/**************************************************************************
 * CONSTANTS
 ***************************************************************************/

type MissingField = "editor_links" | "media_urls" | "publish_status";

// English labels are the single source of truth. Customer-facing replies
// are generated by Claude in the customer's language at runtime; these
// English strings are what we pass to Claude for natural translation.
const MISSING_LABELS_EN: Record<MissingField, string> = {
  editor_links: "the editor link(s)",
  media_urls: "an image or video showing the issue",
  publish_status: "whether the page is published or only saved",
};

const PUBLISH_STATUS_LABEL: Record<"published" | "only_save", string> = {
  published: "Allowed to publish",
  only_save: "Only Save",
};

/**************************************************************************
 * URL FILTERING
 ***************************************************************************/

function filterValidUrls(urls: string[] | undefined): string[] {
  if (!Array.isArray(urls)) return [];
  return urls.filter((u) => typeof u === "string" && u.length > 0 && !looksLikePlaceholder(u));
}

/**************************************************************************
 * NOTE FORMAT
 ***************************************************************************/

interface AppsNoteFields {
  issueDescription: string;
  editorLinks: string[];
  mediaUrls: string[];
  publishStatus: "published" | "only_save";
}

function formatAppsNoteContent(fields: AppsNoteFields, ticketUrl: string): string {
  // Defense in depth: filter placeholders again at the formatter so it stays
  // correct even if a caller skips the missing-info gate.
  const editors = filterValidUrls(fields.editorLinks);
  const media = filterValidUrls(fields.mediaUrls);

  const issueLine = `Issue: ${fields.issueDescription}, editor: ${editors.join(", ")}, media: ${media.join(", ")}`;
  const statusLine = PUBLISH_STATUS_LABEL[fields.publishStatus];

  return `${issueLine}\nTicket: ${ticketUrl}\n${statusLine}`;
}

/**************************************************************************
 * MAIN HANDLER
 ***************************************************************************/

async function escalateAppsIssueHandler(
  input: EscalateAppsInput,
  textsFetcher: (sessionId: string) => Promise<string[]> = fetchCustomerTexts
): Promise<EscalateAppsOutput> {
  const customerTexts = await textsFetcher(input.crisp_session_id ?? "");

  // Editor-exit gate FIRST. From Hugo's conversation perspective, asking
  // the customer to exit the editor happens BEFORE any other escalation
  // sub-step (access check, info validation) so the technical team can
  // start work without save conflicts.
  const editorExit = await requireEditorExit(
    input.user_exited_editor,
    input.customer_last_message_text
  );
  if (!editorExit.ready) {
    return {
      issue_summary:
        "Need confirmation that the customer has exited the editor before escalating.",
      session_match: undefined,
      ...editorExit.output,
    } as EscalateAppsOutput;
  }

  const sentEditors = filterValidUrls(input.editor_links).filter((e) => urlAppearsInMessages(e, customerTexts));
  const validEditors = sentEditors.filter((e) => isEditorLink(e));

  // The customer pasted a link for the editor slot, but it is not a PageFly
  // editor link (e.g. a homepage). Ask again with the editor-link guide image.
  if (validEditors.length === 0 && sentEditors.length > 0) {
    return {
      issue_summary: "The link provided is not a PageFly editor link.",
      is_ready_for_escalation: false,
      missing_info: ["editor_links"],
      crisp_note: { content: "", formatted_message: "" },
      next_step_for_user: await pickWrongEditorLinkMessage(input.customer_last_message_text),
      note_posted: false,
      note_post_error:
        "The customer's link is not a PageFly editor link (wrong type). Hugo must ask for the real editor link; do NOT escalate with a homepage/preview/admin link.",
    };
  }

  const validMedia = filterValidUrls(input.media_urls);

  const consent = await groundPublishConsent(
    customerTexts,
    input.publish_status === "published" ? "publish"
      : input.publish_status === "only_save" ? "save" : undefined
  );

  const missing: MissingField[] = [];
  if (validEditors.length === 0) missing.push("editor_links");
  if (validMedia.length === 0) missing.push("media_urls");
  if (consent === "unknown") {
    missing.push("publish_status");
  }

  if (missing.length > 0) {
    const labelsEn = missing.map((key) => MISSING_LABELS_EN[key]).join(", ");
    return {
      issue_summary: "Need more information before escalating to the technical team.",
      is_ready_for_escalation: false,
      missing_info: missing,
      crisp_note: { content: "", formatted_message: "" },
      next_step_for_user: await pickMissingInfoMessage(input.customer_last_message_text, labelsEn),
      note_posted: false,
      note_post_error:
        "Not ready for escalation — Hugo MUST ask the user for the real editor link(s), image/video showing the issue, and publish status. Do NOT fabricate URLs or status values.",
    };
  }

  // The note (TS-facing) must always be English. Translate if Hugo passed Vietnamese.
  const issueDescriptionEn = await translateIssueToEnglish(input.issue_description);

  const noteResult: PostNoteResult = await tryPostNoteWithScoring({
    hintedSessionId: input.crisp_session_id,
    customerLastMessageText: input.customer_last_message_text,
    dedupKey: makeDedupKey("escalate_apps_issue", validEditors.join(",")),
    fields: {
      issueDescription: issueDescriptionEn,
      editorLinks: validEditors,
      mediaUrls: validMedia,
      publishStatus: consent === "publish" ? "published" : "only_save",
    },
    providedTicketUrl: input.ticket_url,
    formatNote: formatAppsNoteContent,
  });

  if (noteResult.posted) {
    console.log(
      `[escalate_apps_issue] match: session=${noteResult.sessionUsed} source=${noteResult.sessionSource} score=${noteResult.match?.score ?? "n/a"} signals=[${noteResult.match?.signalsMatched.join(", ") ?? ""}] posted=true`
    );
  } else {
    console.error(
      `[escalate_apps_issue] match: posted=false error=${noteResult.error}`
    );
  }

  return {
    issue_summary: input.issue_description,
    is_ready_for_escalation: true,
    missing_info: [],
    crisp_note: {
      content: noteResult.noteContent,
      formatted_message: noteResult.noteContent,
    },
    next_step_for_user: await pickWaitMessage(input.customer_last_message_text),
    note_posted: noteResult.posted,
    note_post_error: noteResult.error,
    session_match: noteResult.match
      ? {
          score: noteResult.match.score,
          signals_matched: noteResult.match.signalsMatched,
          threshold_met: noteResult.match.thresholdMet,
        }
      : undefined,
  };
}

/**************************************************************************
 * EXPORTS
 ***************************************************************************/

export { escalateAppsIssueHandler, formatAppsNoteContent };
